import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/theme/app_colors.dart';
import '../../core/theme/app_spacing.dart';
import '../../core/theme/app_typography.dart';
import '../../shared/widgets/nuveli_background.dart';
import '../../shared/widgets/nuveli_bottom_nav.dart';
import '../../shared/widgets/nuveli_button.dart';
import 'providers/ai_coach_provider.dart';
import 'widgets/coach_header.dart';
import 'widgets/daily_recap_card.dart';
import 'widgets/insights_grid.dart';
import 'widgets/nutrition_score_ring.dart';
import 'widgets/recommended_for_you_card.dart';
import 'widgets/todays_insight_card.dart';
import 'widgets/todays_summary_mini.dart';

/// AI Coach Insights screen (Görsel 8).
///
/// Aggregates everything generated by the GPT-4o coach for today:
/// nutrition score, main insight, four small tips, today's macros,
/// a recommended action, and a daily recap.
class AICoachScreen extends ConsumerWidget {
  const AICoachScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final coachAsync = ref.watch(aiCoachProvider);

    return NuveliBackground(
      child: Scaffold(
        backgroundColor: Colors.transparent,
        body: SafeArea(
          bottom: false,
          child: coachAsync.when(
            loading: () => const _CoachSkeleton(),
            error: (error, _) => _CoachError(
              onRetry: () =>
                  ref.read(aiCoachProvider.notifier).refresh(),
            ),
            data: (data) => RefreshIndicator(
              color: AppColors.primaryCyan,
              backgroundColor: AppColors.cardBackground,
              onRefresh: () =>
                  ref.read(aiCoachProvider.notifier).refresh(),
              child: CustomScrollView(
                physics: const AlwaysScrollableScrollPhysics(
                  parent: BouncingScrollPhysics(),
                ),
                slivers: [
                  SliverToBoxAdapter(
                    child: CoachHeader(
                      onBack: () => Navigator.maybePop(context),
                      onSettings: () {
                        // TODO: navigate to coach settings (notifications, frequency)
                      },
                    ),
                  ),
                  SliverPadding(
                    padding: const EdgeInsets.fromLTRB(
                      AppSpacing.md,
                      0,
                      AppSpacing.md,
                      100, // breathing room above bottom nav
                    ),
                    sliver: SliverList(
                      delegate: SliverChildListDelegate.fixed([
                        const SizedBox(height: 8),
                        NutritionScoreRing(
                          score: data.nutritionScore.value,
                          label: data.nutritionScore.label,
                        ),
                        const SizedBox(height: 28),
                        TodaysInsightCard(insight: data.mainInsight),
                        const SizedBox(height: 16),
                        InsightsGrid(insights: data.smallInsights),
                        const SizedBox(height: 28),
                        TodaysSummaryMini(macros: data.todaysMacros),
                        const SizedBox(height: 28),
                        RecommendedForYouCard(
                          recommendation: data.recommendation,
                          onApply: () => ref
                              .read(aiCoachProvider.notifier)
                              .applyTip(),
                          onSeeDetails: () {
                            // TODO: open details bottom sheet
                          },
                        ),
                        const SizedBox(height: 16),
                        DailyRecapCard(recap: data.dailyRecap),
                      ]),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ),
        bottomNavigationBar: NuveliBottomNav(
          currentIndex: 3,
          onTap: (_) {
            // Wired up in Chat 12 (Navigation & Routing).
          },
        ),
      ),
    );
  }
}

/// Minimal loading skeleton — keeps the layout footprint identical so
/// content doesn't jump when it lands.
class _CoachSkeleton extends StatelessWidget {
  const _CoachSkeleton();

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(AppSpacing.md),
      child: Column(
        children: [
          const SizedBox(height: 48),
          _shimmerCircle(200),
          const SizedBox(height: 28),
          _shimmerBox(double.infinity, 120),
          const SizedBox(height: 16),
          Row(
            children: [
              Expanded(child: _shimmerBox(double.infinity, 110)),
              const SizedBox(width: 12),
              Expanded(child: _shimmerBox(double.infinity, 110)),
            ],
          ),
          const SizedBox(height: 12),
          Row(
            children: [
              Expanded(child: _shimmerBox(double.infinity, 110)),
              const SizedBox(width: 12),
              Expanded(child: _shimmerBox(double.infinity, 110)),
            ],
          ),
        ],
      ),
    );
  }

  Widget _shimmerBox(double w, double h) {
    return Container(
      width: w,
      height: h,
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.04),
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: Colors.white.withOpacity(0.06)),
      ),
    );
  }

  Widget _shimmerCircle(double size) {
    return Container(
      width: size,
      height: size,
      decoration: BoxDecoration(
        color: Colors.white.withOpacity(0.04),
        shape: BoxShape.circle,
        border: Border.all(color: Colors.white.withOpacity(0.06)),
      ),
    );
  }
}

class _CoachError extends StatelessWidget {
  final VoidCallback onRetry;

  const _CoachError({required this.onRetry});

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              Icons.cloud_off_rounded,
              size: 48,
              color: AppColors.textSecondary,
            ),
            const SizedBox(height: 16),
            Text(
              "Couldn't load today's coaching",
              textAlign: TextAlign.center,
              style: AppTypography.cardTitle.copyWith(
                color: AppColors.textPrimary,
                fontWeight: FontWeight.w600,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              'Check your connection and try again.',
              textAlign: TextAlign.center,
              style: AppTypography.bodyMedium.copyWith(
                color: AppColors.textSecondary,
              ),
            ),
            const SizedBox(height: 24),
            SizedBox(
              width: 180,
              child: NuveliButton.primary(
                label: 'Retry',
                onPressed: onRetry,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
